# Generated by Django 5.2.15 on 2026-06-24 16:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_expense_charge'),
        ('patients', '0002_professionalnote_professionalpatientassignment'),
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('starts_at', models.DateTimeField(verbose_name='inicio')),
                ('ends_at', models.DateTimeField(verbose_name='fim')),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('scheduled', 'Agendado'), ('completed', 'Realizado'), ('canceled', 'Cancelado'), ('no_show', 'Faltou')], default='scheduled', max_length=20, verbose_name='status')),
                ('booking_source', models.CharField(choices=[('patient', 'Paciente'), ('professional', 'Profissional'), ('administration', 'Administracao'), ('management', 'Gerencia')], default='administration', max_length=30, verbose_name='origem do agendamento')),
                ('service_units', models.PositiveSmallIntegerField(default=1, verbose_name='atendimentos consumidos')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('external_provider', models.CharField(blank=True, max_length=40, verbose_name='provedor externo')),
                ('external_event_id', models.CharField(blank=True, max_length=120, verbose_name='id evento externo')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='baixado em')),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_appointments', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='team.professional')),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamentos',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('total_sessions', models.PositiveSmallIntegerField(verbose_name='total de aulas/atendimentos')),
                ('used_sessions', models.PositiveSmallIntegerField(default=0, verbose_name='aulas/atendimentos usados')),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='inicio')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('finished', 'Finalizado'), ('expired', 'Expirado'), ('canceled', 'Cancelado')], default='active', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_packages', to='billing.membership')),
            ],
            options={
                'verbose_name': 'pacote de atendimentos',
                'verbose_name_plural': 'pacotes de atendimentos',
                'ordering': ['membership__patient__full_name', '-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='ServiceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('units', models.PositiveSmallIntegerField(default=1, verbose_name='atendimentos consumidos')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registrado em')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='service_usage', to='scheduling.appointment')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_service_usages', to=settings.AUTH_USER_MODEL)),
                ('service_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='scheduling.servicepackage')),
            ],
            options={
                'verbose_name': 'baixa de atendimento',
                'verbose_name_plural': 'baixas de atendimento',
                'ordering': ['-registered_at'],
            },
        ),
    ]
