# Generated by Django 5.2.15 on 2026-06-24 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='scheduling.appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('requested', 'Solicitado'), ('scheduled', 'Agendado'), ('completed', 'Realizado'), ('rescheduled', 'Reagendado'), ('canceled', 'Cancelado'), ('no_show', 'Faltou')], default='scheduled', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='ProfessionalAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terca'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sabado'), (6, 'Domingo')], verbose_name='dia da semana')),
                ('starts_at', models.TimeField(verbose_name='inicio')),
                ('ends_at', models.TimeField(verbose_name='fim')),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='valido a partir de')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='valido ate')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.CharField(blank=True, max_length=180, verbose_name='observacoes')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='team.professional')),
            ],
            options={
                'verbose_name': 'disponibilidade profissional',
                'verbose_name_plural': 'disponibilidades profissionais',
                'ordering': ['professional__full_name', 'weekday', 'starts_at'],
                'constraints': [models.UniqueConstraint(fields=('professional', 'weekday', 'starts_at', 'ends_at', 'valid_from'), name='unique_professional_availability_window')],
            },
        ),
    ]
