# Generated by Codex on 2026-06-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_appointment_rescheduled_from_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentSeries",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="atualizado em")),
                (
                    "repeat_type",
                    models.CharField(
                        choices=[("weekly", "Semanal")],
                        default="weekly",
                        max_length=20,
                        verbose_name="tipo de repeticao",
                    ),
                ),
                ("interval_weeks", models.PositiveSmallIntegerField(default=1, verbose_name="intervalo em semanas")),
                ("repeat_until", models.DateField(blank=True, null=True, verbose_name="repetir ate")),
                ("occurrences_count", models.PositiveSmallIntegerField(default=1, verbose_name="quantidade de sessoes")),
                ("notes", models.CharField(blank=True, max_length=180, verbose_name="observacoes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointment_series",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "serie de agendamentos",
                "verbose_name_plural": "series de agendamentos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="scheduling.appointmentseries",
                verbose_name="serie",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="slot_capacity",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="capacidade da sessao"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="slot_group",
            field=models.CharField(blank=True, db_index=True, max_length=36, verbose_name="grupo do horario"),
        ),
        migrations.AddField(
            model_name="professionalavailability",
            name="session_capacity",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="capacidade padrao da sessao"),
        ),
    ]
