# Generated by Django 5.2.15 on 2026-06-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_appointmentseries_appointment_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalavailability',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='exclusao solicitada em'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='exclusao solicitada em'),
        ),
    ]
