# Generated by Django 5.2.15 on 2026-06-30 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_membership_one_active_membership_per_patient_and_more'),
        ('scheduling', '0004_professionalavailability_deletion_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='billing.serviceplan', verbose_name='plano/servico'),
        ),
    ]
