# Generated by Django 5.2.15 on 2026-07-02 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_appointment_service_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackageAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('delta_sessions', models.SmallIntegerField(verbose_name='ajuste de creditos')),
                ('reason', models.CharField(choices=[('appointment_no_credit', 'Credito adicionado na baixa'), ('manual_correction', 'Correcao manual')], default='manual_correction', max_length=40, verbose_name='motivo')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_adjustments', to='scheduling.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_package_adjustments', to=settings.AUTH_USER_MODEL)),
                ('service_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='scheduling.servicepackage')),
            ],
            options={
                'verbose_name': 'ajuste de credito',
                'verbose_name_plural': 'ajustes de credito',
                'ordering': ['-created_at'],
            },
        ),
    ]
