# Generated by Django 5.2.15 on 2026-07-13 00:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_deletion_requested_at'),
        ('scheduling', '0006_servicepackageadjustment'),
        ('team', '0003_employee_deletion_requested_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('present', 'Presente'), ('absent', 'Falta'), ('justified_absence', 'Falta justificada'), ('rescheduled', 'Reagendada'), ('clinic_canceled', 'Cancelada pela clinica'), ('replacement', 'Reposicao')], max_length=30, verbose_name='presenca')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registrado em')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='scheduling.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='patients.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='team.professional')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'presenca',
                'verbose_name_plural': 'presencas',
                'ordering': ['-appointment__starts_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('feeling', models.CharField(choices=[('no_pain', 'Sem dor'), ('light_pain', 'Dor leve'), ('moderate_pain', 'Dor moderada'), ('intense_pain', 'Dor intensa')], max_length=30, verbose_name='como esta se sentindo')),
                ('pain_level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nivel de dor')),
                ('note', models.TextField(blank=True, verbose_name='observacao')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='scheduling.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_checkins', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='patients.patient')),
            ],
            options={
                'verbose_name': 'check-in do paciente',
                'verbose_name_plural': 'check-ins dos pacientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=160, verbose_name='meta')),
                ('main_complaint', models.CharField(blank=True, max_length=220, verbose_name='queixa principal')),
                ('objective', models.TextField(blank=True, verbose_name='objetivos')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('achieved', 'Concluida'), ('paused', 'Pausada'), ('canceled', 'Cancelada')], default='active', max_length=20, verbose_name='status')),
                ('progress_note', models.TextField(blank=True, verbose_name='progresso')),
                ('achieved_at', models.DateTimeField(blank=True, null=True, verbose_name='concluida em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='patients.patient')),
            ],
            options={
                'verbose_name': 'meta do paciente',
                'verbose_name_plural': 'metas dos pacientes',
                'ordering': ['patient__full_name', 'status', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=160, verbose_name='conquista')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('achieved_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='data da conquista')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patient_achievements', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='patients.patient')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='scheduling.patientgoal')),
            ],
            options={
                'verbose_name': 'conquista do paciente',
                'verbose_name_plural': 'conquistas dos pacientes',
                'ordering': ['-achieved_on', 'patient__full_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('kind', models.CharField(choices=[('appointment_day', 'Aula no dia'), ('session_confirmation', 'Confirmacao da sessao'), ('absence_warning', 'Aviso de falta'), ('plan_renewal', 'Renovacao do plano'), ('holiday', 'Feriado'), ('schedule_change', 'Mudanca de horario'), ('reschedule', 'Remarcacao')], max_length=30, verbose_name='tipo')),
                ('channel', models.CharField(choices=[('panel', 'Painel'), ('whatsapp', 'WhatsApp'), ('pwa', 'PWA')], default='panel', max_length=20, verbose_name='canal')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('skipped', 'Ignorada'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='status')),
                ('due_at', models.DateTimeField(db_index=True, verbose_name='programada para')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('idempotency_key', models.CharField(max_length=180, unique=True, verbose_name='chave unica')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_notifications', to='scheduling.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patients.patient')),
            ],
            options={
                'verbose_name': 'notificacao do paciente',
                'verbose_name_plural': 'notificacoes dos pacientes',
                'ordering': ['status', 'due_at'],
            },
        ),
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='data preferida')),
                ('preferred_period', models.CharField(choices=[('morning', 'Manha'), ('afternoon', 'Tarde'), ('evening', 'Noite'), ('any', 'Qualquer horario')], default='any', max_length=20, verbose_name='periodo preferido')),
                ('reason', models.TextField(blank=True, verbose_name='motivo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('declined', 'Recusada'), ('canceled', 'Cancelada')], default='pending', max_length=20, verbose_name='status')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='decidido em')),
                ('decision_note', models.TextField(blank=True, verbose_name='observacao da equipe')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_requests', to='scheduling.appointment')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_reschedule_requests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_requests', to='patients.patient')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reschedule_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reschedule_requests', to='scheduling.appointment')),
            ],
            options={
                'verbose_name': 'solicitacao de remarcacao',
                'verbose_name_plural': 'solicitacoes de remarcacao',
                'ordering': ['status', 'appointment__starts_at'],
            },
        ),
    ]
