# Generated by Django 5.2.15 on 2026-07-13 03:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_whatsappautomationsettings_appointment_day_reminder_hours_before_and_more'),
        ('patients', '0006_patient_deletion_requested_at'),
        ('scheduling', '0007_appointmentattendance_patientcheckin_patientgoal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnotification',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='tentativas'),
        ),
        migrations.AddField(
            model_name='patientnotification',
            name='delivery_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notification', to='core.whatsappmessagelog', verbose_name='registro de envio'),
        ),
        migrations.AddField(
            model_name='patientnotification',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ultima tentativa'),
        ),
        migrations.AddField(
            model_name='patientnotification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='dados operacionais'),
        ),
        migrations.AddField(
            model_name='patientnotification',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=120, verbose_name='referencia do provedor'),
        ),
        migrations.CreateModel(
            name='OperationalCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('event_type', models.CharField(choices=[('holiday', 'Feriado'), ('recess', 'Recesso'), ('special_hours', 'Horario especial'), ('schedule_change', 'Mudanca de horario')], max_length=30, verbose_name='tipo')),
                ('title', models.CharField(max_length=160, verbose_name='titulo')),
                ('starts_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='inicio')),
                ('ends_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='fim')),
                ('starts_at_time', models.TimeField(blank=True, null=True, verbose_name='horario de inicio')),
                ('ends_at_time', models.TimeField(blank=True, null=True, verbose_name='horario de fim')),
                ('affects_schedule', models.BooleanField(default=True, verbose_name='bloqueia novos agendamentos')),
                ('send_notice', models.BooleanField(default=True, verbose_name='gerar aviso aos pacientes afetados')),
                ('message', models.TextField(blank=True, verbose_name='comunicado')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_operational_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento operacional',
                'verbose_name_plural': 'eventos operacionais',
                'ordering': ['starts_on', 'starts_at_time', 'title'],
            },
        ),
        migrations.AddField(
            model_name='patientnotification',
            name='calendar_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='scheduling.operationalcalendarevent', verbose_name='evento operacional'),
        ),
        migrations.CreateModel(
            name='PatientNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('whatsapp_enabled', models.BooleanField(default=True, verbose_name='aceita WhatsApp')),
                ('pwa_enabled', models.BooleanField(default=False, verbose_name='aceita notificacoes do aplicativo')),
                ('appointment_enabled', models.BooleanField(default=True, verbose_name='aceita avisos de agenda')),
                ('financial_enabled', models.BooleanField(default=True, verbose_name='aceita avisos financeiros')),
                ('operational_enabled', models.BooleanField(default=True, verbose_name='aceita comunicados operacionais')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='patients.patient')),
            ],
            options={
                'verbose_name': 'preferencia de notificacao',
                'verbose_name_plural': 'preferencias de notificacao',
            },
        ),
    ]
