from django.urls import path

from scheduling.views import (
    AgendaSettingsUpdateView,
    AppointmentAbsenceView,
    AppointmentCompleteView,
    AppointmentCancelView,
    AppointmentCalendarExportView,
    AppointmentConfirmView,
    AppointmentCreateView,
    AppointmentListView,
    AppointmentRescheduleView,
    AppointmentUpdateView,
    GenerateNotificationsView,
    NotificationCenterView,
    PatientCheckInCreateView,
    PatientGoalCreateView,
    PatientProgressView,
    ProfessionalAvailabilityCreateView,
    ProfessionalAvailabilityDeleteView,
    ProfessionalAvailabilityListView,
    ProfessionalAvailabilityUpdateView,
    RescheduleRequestCreateView,
    RescheduleRequestDecisionView,
    RescheduleRequestListView,
    ServicePackageCreateView,
    ServicePackageAdjustmentListView,
    ServicePackageDeleteView,
    ServicePackageListView,
    ServicePackageUpdateView,
)

app_name = "scheduling"

urlpatterns = [
    path("", AppointmentListView.as_view(), name="appointments"),
    path("configuracoes/", AgendaSettingsUpdateView.as_view(), name="agenda_settings"),
    path("google/ical/", AppointmentCalendarExportView.as_view(), name="appointments_ical"),
    path("novo/", AppointmentCreateView.as_view(), name="appointment_create"),
    path("<int:pk>/confirmar/", AppointmentConfirmView.as_view(), name="appointment_confirm"),
    path("<int:pk>/editar/", AppointmentUpdateView.as_view(), name="appointment_update"),
    path("<int:pk>/reagendar/", AppointmentRescheduleView.as_view(), name="appointment_reschedule"),
    path("<int:pk>/solicitar-remarcacao/", RescheduleRequestCreateView.as_view(), name="reschedule_request_create"),
    path("<int:pk>/cancelar/", AppointmentCancelView.as_view(), name="appointment_cancel"),
    path("<int:pk>/baixar/", AppointmentCompleteView.as_view(), name="appointment_complete"),
    path("<int:pk>/falta/", AppointmentAbsenceView.as_view(), name="appointment_absence"),
    path("remarcacoes/", RescheduleRequestListView.as_view(), name="reschedule_requests"),
    path("remarcacoes/<int:pk>/<slug:action>/", RescheduleRequestDecisionView.as_view(), name="reschedule_request_decision"),
    path("pacientes/<int:patient_pk>/progresso/", PatientProgressView.as_view(), name="patient_progress"),
    path("pacientes/<int:patient_pk>/checkin/", PatientCheckInCreateView.as_view(), name="patient_checkin_create"),
    path("pacientes/<int:patient_pk>/metas/nova/", PatientGoalCreateView.as_view(), name="patient_goal_create"),
    path("notificacoes/", NotificationCenterView.as_view(), name="notifications"),
    path("notificacoes/gerar/", GenerateNotificationsView.as_view(), name="generate_notifications"),
    path("disponibilidades/", ProfessionalAvailabilityListView.as_view(), name="availabilities"),
    path("disponibilidades/nova/", ProfessionalAvailabilityCreateView.as_view(), name="availability_create"),
    path("disponibilidades/<int:pk>/editar/", ProfessionalAvailabilityUpdateView.as_view(), name="availability_update"),
    path("disponibilidades/<int:pk>/excluir/", ProfessionalAvailabilityDeleteView.as_view(), name="availability_delete"),
    path("pacotes/", ServicePackageListView.as_view(), name="packages"),
    path("pacotes/ajustes/", ServicePackageAdjustmentListView.as_view(), name="package_adjustments"),
    path("pacotes/novo/", ServicePackageCreateView.as_view(), name="package_create"),
    path("pacotes/<int:pk>/editar/", ServicePackageUpdateView.as_view(), name="package_update"),
    path("pacotes/<int:pk>/excluir/", ServicePackageDeleteView.as_view(), name="package_delete"),
]
