# Generated by Django 5.2.15 on 2026-06-24 13:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome do plano')),
                ('category', models.CharField(choices=[('pilates', 'Pilates'), ('physiotherapy', 'Fisioterapia'), ('massage', 'Massagem'), ('reiki', 'Reiki'), ('combo', 'Combo')], max_length=30, verbose_name='categoria')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor mensal')),
                ('sessions_per_week', models.PositiveSmallIntegerField(default=2, verbose_name='sessoes por semana')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data de inicio')),
                ('due_day', models.PositiveSmallIntegerField(default=10, verbose_name='dia de vencimento')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='desconto fixo')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('paused', 'Pausada'), ('canceled', 'Cancelada')], default='active', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='patients.patient')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='billing.serviceplan')),
            ],
            options={
                'verbose_name': 'mensalidade',
                'verbose_name_plural': 'mensalidades',
                'ordering': ['patient__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('reference_month', models.DateField(verbose_name='mes de referencia')),
                ('due_date', models.DateField(verbose_name='vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Vencido'), ('canceled', 'Cancelado')], default='pending', max_length=20, verbose_name='status')),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('pix', 'Pix'), ('cash', 'Dinheiro'), ('card', 'Cartao'), ('transfer', 'Transferencia')], default='manual', max_length=20, verbose_name='metodo')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='pago em')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.membership')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-due_date', 'membership__patient__full_name'],
                'constraints': [models.UniqueConstraint(fields=('membership', 'reference_month'), name='one_payment_per_membership_month')],
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('patient',), name='one_active_membership_per_patient'),
        ),
    ]
