# Generated by Django 5.2.15 on 2026-06-24 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('description', models.CharField(max_length=180, verbose_name='descricao')),
                ('category', models.CharField(choices=[('rent', 'Aluguel'), ('payroll', 'Equipe'), ('supplies', 'Insumos'), ('taxes', 'Impostos'), ('systems', 'Sistemas'), ('other', 'Outros')], default='other', max_length=30, verbose_name='categoria')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('due_date', models.DateField(verbose_name='vencimento')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='pago em')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('paid', 'Paga'), ('canceled', 'Cancelada')], default='open', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
            ],
            options={
                'verbose_name': 'despesa',
                'verbose_name_plural': 'despesas',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('description', models.CharField(max_length=180, verbose_name='descricao')),
                ('due_date', models.DateField(verbose_name='vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('received', 'Recebida'), ('overdue', 'Vencida'), ('canceled', 'Cancelada')], default='open', max_length=20, verbose_name='status')),
                ('received_at', models.DateField(blank=True, null=True, verbose_name='recebida em')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='patients.patient')),
            ],
            options={
                'verbose_name': 'cobranca avulsa',
                'verbose_name_plural': 'cobrancas avulsas',
                'ordering': ['-due_date'],
            },
        ),
    ]
