# Generated by Django 5.2.15 on 2026-06-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_expense_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='display_order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='ordem no site'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='highlight_badge',
            field=models.CharField(blank=True, max_length=40, verbose_name='selo de destaque'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='public_description',
            field=models.TextField(blank=True, verbose_name='descricao publica'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='show_on_website',
            field=models.BooleanField(default=False, verbose_name='exibir no site'),
        ),
    ]
