# Generated by Django 5.2.15 on 2026-06-30 02:36

from django.db import migrations, models


def populate_included_sessions(apps, schema_editor):
    service_plan_model = apps.get_model("billing", "ServicePlan")
    for plan in service_plan_model.objects.all():
        duration_months = max(getattr(plan, "duration_months", 1) or 1, 1)
        plan.included_sessions = max((plan.sessions_per_week or 1) * 4 * duration_months, 1)
        plan.save(update_fields=["included_sessions"])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_serviceplan_deletion_requested_at'),
        ('patients', '0006_patient_deletion_requested_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='one_active_membership_per_patient',
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='duration_months',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='duracao do ciclo em meses'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='included_sessions',
            field=models.PositiveSmallIntegerField(default=8, verbose_name='atendimentos incluidos no ciclo'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='plan_type',
            field=models.CharField(choices=[('recurring', 'Plano recorrente'), ('single', 'Servico avulso')], default='recurring', max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='category',
            field=models.CharField(choices=[('pilates', 'Pilates'), ('physiotherapy', 'Fisioterapia'), ('massage', 'Massagem'), ('reiki', 'Reiki'), ('combo', 'Combo'), ('other', 'Outro servico')], max_length=30, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='serviceplan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor do ciclo'),
        ),
        migrations.RunPython(populate_included_sessions, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('patient', 'plan'), name='one_active_membership_per_patient_plan'),
        ),
    ]
