# Generated by Django 5.2.15 on 2026-06-30 13:31

import django.db.models.deletion
from django.db import migrations, models


def backfill_payment_patient_and_description(apps, schema_editor):
    Payment = apps.get_model("billing", "Payment")
    for payment in Payment.objects.select_related("membership__patient", "membership__plan").filter(membership__isnull=False):
        payment.patient_id = payment.membership.patient_id
        payment.description = payment.description or payment.membership.plan.name
        payment.item_type = "membership"
        payment.save(update_fields=["patient", "description", "item_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_membership_one_active_membership_per_patient_and_more'),
        ('patients', '0006_patient_deletion_requested_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='one_payment_per_membership_month',
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=180, verbose_name='descricao do item'),
        ),
        migrations.AddField(
            model_name='payment',
            name='item_type',
            field=models.CharField(choices=[('membership', 'Mensalidade'), ('service', 'Servico avulso'), ('single_session', 'Sessao avulsa'), ('other', 'Outro pagamento')], default='membership', max_length=30, verbose_name='item/referencia'),
        ),
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.membership'),
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-due_date', 'patient__full_name', 'membership__patient__full_name'], 'verbose_name': 'pagamento', 'verbose_name_plural': 'pagamentos'},
        ),
        migrations.RunPython(backfill_payment_patient_and_description, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('membership__isnull', False)), fields=('membership', 'reference_month'), name='one_payment_per_membership_month'),
        ),
    ]
