# Generated by Django 5.2.15 on 2026-06-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_remove_payment_one_payment_per_membership_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceplan',
            name='delivery_mode',
            field=models.CharField(choices=[('in_person', 'Presencial'), ('digital', 'Digital'), ('hybrid', 'Hibrido')], default='in_person', help_text='Use Digital para planos apenas do Lume em Casa, ou Hibrido para plano presencial com acesso digital.', max_length=20, verbose_name='modalidade'),
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='grants_homecare_access',
            field=models.BooleanField(default=False, help_text='Libera automaticamente o acesso do paciente ao modulo Lume em Casa enquanto o vinculo/plano estiver ativo.', verbose_name='Acesso ao Lume em Casa'),
        ),
    ]
