# Generated by Django 5.2.15 on 2026-07-02 23:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_serviceplan_delivery_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('date', models.DateField(default=django.utils.timezone.localdate, unique=True, verbose_name='data do caixa')),
                ('payments_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='recebimentos')),
                ('charges_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='cobrancas avulsas')),
                ('expenses_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='despesas pagas')),
                ('cash_expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='dinheiro esperado')),
                ('cash_counted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='dinheiro conferido')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fechado em')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_closings', to=settings.AUTH_USER_MODEL, verbose_name='fechado por')),
            ],
            options={
                'verbose_name': 'fechamento de caixa',
                'verbose_name_plural': 'fechamentos de caixa',
                'ordering': ['-date'],
            },
        ),
    ]
