# Generated by Django 5.2.15 on 2026-06-24 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('membership_due_reminder_days', models.PositiveSmallIntegerField(default=5, help_text='Quantidade de dias para destacar mensalidades proximas do vencimento.', verbose_name='dias antes do vencimento')),
            ],
            options={
                'verbose_name': 'configuracao da clinica',
                'verbose_name_plural': 'configuracoes da clinica',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Criado'), ('updated', 'Atualizado'), ('deleted', 'Excluido')], max_length=20, verbose_name='acao')),
                ('app_label', models.CharField(max_length=80, verbose_name='app')),
                ('model_name', models.CharField(max_length=80, verbose_name='modelo')),
                ('object_id', models.CharField(blank=True, max_length=80, verbose_name='id do objeto')),
                ('object_repr', models.CharField(max_length=255, verbose_name='objeto')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='alteracoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
