# Generated by Django 5.2.15 on 2026-06-25 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereco'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='business_days',
            field=models.CharField(default='Segunda a sexta', max_length=120, verbose_name='dias de atendimento'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='cancellation_deadline_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Prazo minimo recomendado para cancelar sem intervencao da equipe.', verbose_name='prazo de cancelamento em horas'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='cancellation_policy',
            field=models.TextField(blank=True, verbose_name='regra de cancelamento'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='clinic_name',
            field=models.CharField(default='Lume Gestao', max_length=140, verbose_name='nome da clinica'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='closing_time',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='horario de fechamento'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='default_membership_due_day',
            field=models.PositiveSmallIntegerField(default=10, help_text='Dia sugerido para novas mensalidades. Use entre 1 e 28.', verbose_name='dia padrao de vencimento'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='logo',
            field=models.FileField(blank=True, upload_to='clinic/', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='opening_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='horario de abertura'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='telefone'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='rescheduling_deadline_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Prazo minimo recomendado para reagendar sem intervencao da equipe.', verbose_name='prazo de reagendamento em horas'),
        ),
        migrations.AddField(
            model_name='clinicsettings',
            name='rescheduling_policy',
            field=models.TextField(blank=True, verbose_name='regra de reagendamento'),
        ),
    ]
