# Generated by Django 5.2.15 on 2026-06-26 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_expense_categories'),
        ('core', '0003_googlecalendarintegration_whatsappintegration'),
        ('patients', '0005_professionalnote_structured_data_and_more'),
        ('scheduling', '0003_appointmentseries_appointment_series_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappintegration',
            name='clinic_whatsapp_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='numero da clinica'),
        ),
        migrations.AddField(
            model_name='whatsappintegration',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='conectado em'),
        ),
        migrations.CreateModel(
            name='WhatsAppMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('template_type', models.CharField(choices=[('appointment', 'Mensagem de agendamento'), ('charge', 'Mensagem de cobranca'), ('birthday', 'Mensagem de aniversario')], max_length=20, unique=True, verbose_name='tipo')),
                ('title', models.CharField(max_length=120, verbose_name='titulo')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descricao')),
                ('body', models.TextField(verbose_name='mensagem')),
                ('send_time', models.TimeField(blank=True, null=True, verbose_name='horario do envio')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_templates_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'modelo de mensagem WhatsApp',
                'verbose_name_plural': 'modelos de mensagens WhatsApp',
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('recipient_name', models.CharField(max_length=180, verbose_name='destinatario')),
                ('recipient_number', models.CharField(max_length=30, verbose_name='numero')),
                ('rendered_message', models.TextField(verbose_name='mensagem enviada')),
                ('status', models.CharField(choices=[('sent', 'Enviada'), ('dry_run', 'Simulada'), ('failed', 'Falhou')], default='dry_run', max_length=20, verbose_name='status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviada em')),
                ('provider_reference', models.CharField(blank=True, max_length=120, verbose_name='referencia do provedor')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='retorno da integracao')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='scheduling.appointment')),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='billing.charge')),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='core.whatsappintegration')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='patients.patient')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='billing.payment')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.whatsappmessagetemplate')),
            ],
            options={
                'verbose_name': 'historico de WhatsApp',
                'verbose_name_plural': 'historico de WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
