# Generated by Django 5.2.15 on 2026-06-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_whatsapp_embedded_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendarintegration',
            name='calendar_feed_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='link .ics criado em'),
        ),
        migrations.AddField(
            model_name='googlecalendarintegration',
            name='calendar_feed_enabled',
            field=models.BooleanField(default=False, verbose_name='link .ics ativo'),
        ),
        migrations.AddField(
            model_name='googlecalendarintegration',
            name='calendar_feed_token',
            field=models.CharField(blank=True, max_length=96, unique=True, verbose_name='token do calendario .ics'),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='charge_overdue_days_after',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='dias apos vencimento avulso'),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='charge_overdue_enabled',
            field=models.BooleanField(default=True, verbose_name='enviar aviso de cobranca avulsa vencida'),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='membership_due_days_before',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='dias antes do vencimento'),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='membership_due_on_date',
            field=models.BooleanField(default=True, verbose_name='enviar tambem no dia do vencimento'),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='membership_due_reminders_enabled',
            field=models.BooleanField(default=True, verbose_name='enviar lembretes de mensalidade a vencer'),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='membership_overdue_days_after',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='dias apos o vencimento'),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='membership_overdue_enabled',
            field=models.BooleanField(default=True, verbose_name='enviar aviso de mensalidade vencida'),
        ),
        migrations.AddField(
            model_name='whatsappmessagetemplate',
            name='meta_template_language',
            field=models.CharField(default='pt_BR', max_length=10, verbose_name='idioma do template Meta'),
        ),
        migrations.AddField(
            model_name='whatsappmessagetemplate',
            name='meta_template_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='nome do template aprovado na Meta'),
        ),
    ]
