# Generated by Django 5.2.15 on 2026-07-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_googlecalendarintegration_calendar_feed_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappintegration',
            name='provider',
            field=models.CharField(choices=[('meta', 'Meta Cloud API'), ('web_gateway', 'WhatsApp Web temporario'), ('twilio', 'Twilio')], default='meta', max_length=20, verbose_name='provedor'),
        ),
    ]
