# Generated by Django 5.2.15 on 2026-07-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_whatsappintegration_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='appointment_day_reminder_hours_before',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='horas antes do lembrete no dia'),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='appointment_day_reminders_enabled',
            field=models.BooleanField(default=True, verbose_name='enviar lembrete no dia da consulta'),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='low_credit_reminders_enabled',
            field=models.BooleanField(default=True, verbose_name='avisar saldo baixo de atendimentos'),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='low_credit_threshold',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='saldo minimo para alerta'),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='package_expiry_days_before',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='dias antes da validade do pacote'),
        ),
        migrations.AddField(
            model_name='whatsappautomationsettings',
            name='package_expiry_reminders_enabled',
            field=models.BooleanField(default=True, verbose_name='avisar pacote perto da validade'),
        ),
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='automation_key',
            field=models.CharField(blank=True, db_index=True, max_length=180, verbose_name='chave da automacao'),
        ),
    ]
