# Generated by Django 5.2.15 on 2026-07-13 19:02

import django.db.models.deletion
from django.db import migrations, models


def create_session_soon_defaults(apps, schema_editor):
    Template = apps.get_model("core", "WhatsAppMessageTemplate")
    Rule = apps.get_model("core", "WhatsAppAutomationRule")
    Settings = apps.get_model("core", "WhatsAppAutomationSettings")
    settings = Settings.objects.filter(pk=1).first()

    appointment = Template.objects.filter(template_type="appointment").order_by("pk").first()
    if appointment:
        Rule.objects.get_or_create(
            name="Lembrete de sessao - 24 horas",
            is_system=True,
            defaults={
                "template": appointment,
                "trigger": "appointment_before",
                "hours_before": settings.appointment_reminder_hours_before if settings else 24,
                "active": settings.appointment_reminders_enabled if settings else True,
            },
        )

    session_soon, _created = Template.objects.get_or_create(
        template_type="session_soon",
        defaults={
            "title": "Sessao proxima",
            "description": "Lembrete enviado pouco antes do inicio da sessao.",
            "body": "Ola, [Paciente]! Sua sessao com [Profissional] comeca em aproximadamente uma hora, as [Horario]. Esperamos voce na [Clinica].",
            "active": True,
        },
    )
    Rule.objects.get_or_create(
        name="Sessao proxima - 1 hora",
        is_system=True,
        defaults={
            "template": session_soon,
            "trigger": "appointment_before",
            "hours_before": settings.appointment_day_reminder_hours_before if settings else 1,
            "active": settings.appointment_day_reminders_enabled if settings else True,
        },
    )


def remove_session_soon_defaults(apps, schema_editor):
    Rule = apps.get_model("core", "WhatsAppAutomationRule")
    Rule.objects.filter(
        is_system=True,
        name__in=["Lembrete de sessao - 24 horas", "Sessao proxima - 1 hora"],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_emaildeliveryevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessagetemplate',
            name='template_type',
            field=models.CharField(choices=[('appointment', 'Mensagem de agendamento'), ('session_soon', 'Sessao proxima'), ('charge', 'Mensagem de cobranca'), ('birthday', 'Mensagem de aniversario'), ('custom', 'Modelo personalizado')], max_length=20, verbose_name='tipo'),
        ),
        migrations.CreateModel(
            name='WhatsAppAutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome da automacao')),
                ('trigger', models.CharField(choices=[('appointment_before', 'Antes da sessao'), ('manual', 'Somente envio manual')], default='appointment_before', max_length=40, verbose_name='rotina')),
                ('hours_before', models.PositiveSmallIntegerField(default=1, verbose_name='horas antes da sessao')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('is_system', models.BooleanField(default=False, verbose_name='regra do sistema')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_rules', to='core.whatsappmessagetemplate', verbose_name='modelo de mensagem')),
            ],
            options={
                'verbose_name': 'regra de automacao WhatsApp',
                'verbose_name_plural': 'regras de automacao WhatsApp',
                'ordering': ['is_system', 'hours_before', 'name'],
            },
        ),
        migrations.RunPython(create_session_soon_defaults, remove_session_soon_defaults),
    ]
