# Generated by Django 5.2.15 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_whatsappmessagetemplate_template_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessagelog",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="tentativas"),
        ),
        migrations.AddField(
            model_name="whatsappmessagelog",
            name="next_attempt_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="proxima tentativa"),
        ),
    ]
