# Generated by Django 5.2.15 on 2026-06-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('question', models.CharField(max_length=180, verbose_name='pergunta')),
                ('answer', models.TextField(verbose_name='resposta')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'FAQ do site',
                'verbose_name_plural': 'FAQs do site',
                'ordering': ['display_order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('clinic_name', models.CharField(default='Lume Studio Fisio', max_length=140, verbose_name='nome exibido')),
                ('hero_title', models.CharField(default='Movimento consciente para reabilitar, prevenir e viver melhor.', max_length=180, verbose_name='titulo principal')),
                ('hero_subtitle', models.TextField(default='Pilates, fisioterapia, massagem e Reiki em um atendimento acolhedor, humano e pensado para a sua rotina.', verbose_name='subtitulo principal')),
                ('institutional_title', models.CharField(default='Cuidado que acompanha cada fase', max_length=140, verbose_name='titulo institucional')),
                ('institutional_text', models.TextField(default='A Lume une tecnica, escuta e acompanhamento proximo para ajudar cada paciente a recuperar funcao, ganhar autonomia e manter o corpo em movimento com seguranca.', verbose_name='texto institucional')),
                ('primary_cta_text', models.CharField(default='Agendar pelo WhatsApp', max_length=60, verbose_name='texto do CTA principal')),
                ('system_cta_text', models.CharField(default='Acessar sistema', max_length=60, verbose_name='texto do CTA do sistema')),
                ('whatsapp_url', models.URLField(default='https://wa.me/message/GTYUJB6MIJJUJ1', verbose_name='link do WhatsApp')),
                ('system_url', models.URLField(default='https://sistema.clinicafisiolume.com.br', help_text='URL publica do sistema operacional da clinica.', verbose_name='link do sistema')),
                ('instagram_url', models.URLField(default='https://www.instagram.com/lumestudiofisio/', verbose_name='link do Instagram')),
                ('address_line', models.CharField(blank=True, default='Av. Sao Luiz, 245', max_length=255, verbose_name='endereco exibido')),
                ('city_name', models.CharField(default='Penedo, AL', max_length=120, verbose_name='cidade/regiao')),
                ('business_hours', models.CharField(blank=True, default='Segunda a sexta, das 8h as 18h', max_length=120, verbose_name='horario exibido')),
                ('seo_title', models.CharField(default='Lume Studio Fisio | Pilates, Fisioterapia e Bem-estar em Penedo/AL', max_length=160, verbose_name='SEO title')),
                ('seo_description', models.CharField(default='Conheca a Lume Studio Fisio em Penedo/AL para Pilates, fisioterapia, massagem e Reiki com atendimento acolhedor e agendamento rapido pelo WhatsApp.', max_length=255, verbose_name='SEO description')),
                ('assistant_enabled', models.BooleanField(default=True, verbose_name='assistente virtual ativo')),
                ('whatsapp_clicks', models.PositiveIntegerField(default=0, verbose_name='cliques no WhatsApp')),
                ('system_clicks', models.PositiveIntegerField(default=0, verbose_name='cliques no sistema')),
            ],
            options={
                'verbose_name': 'configuracao do site',
                'verbose_name_plural': 'configuracoes do site',
            },
        ),
        migrations.CreateModel(
            name='WebsiteTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('author_name', models.CharField(max_length=120, verbose_name='nome')),
                ('author_role', models.CharField(blank=True, max_length=140, verbose_name='identificacao')),
                ('body', models.TextField(verbose_name='depoimento')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'depoimento do site',
                'verbose_name_plural': 'depoimentos do site',
                'ordering': ['display_order', 'author_name'],
            },
        ),
    ]
