# Generated by Django 5.2.15 on 2026-07-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=140, verbose_name='titulo')),
                ('image', models.ImageField(upload_to='website/gallery/', verbose_name='imagem')),
                ('alt_text', models.CharField(max_length=180, verbose_name='texto alternativo')),
                ('external_url', models.URLField(blank=True, verbose_name='link externo')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'imagem da galeria',
                'verbose_name_plural': 'imagens da galeria',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteNewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('consented_at', models.DateTimeField(verbose_name='consentimento em')),
                ('source', models.CharField(default='landing', max_length=60, verbose_name='origem')),
                ('brevo_contact_synced', models.BooleanField(default=False, verbose_name='sincronizado com Brevo')),
                ('brevo_error', models.TextField(blank=True, verbose_name='erro da Brevo')),
            ],
            options={
                'verbose_name': 'inscrito da landing',
                'verbose_name_plural': 'inscritos da landing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=120, verbose_name='titulo')),
                ('description', models.TextField(verbose_name='descricao')),
                ('icon', models.CharField(blank=True, help_text='Nome de um icone Material Symbols, como accessibility_new ou spa.', max_length=40, verbose_name='icone')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'atendimento do site',
                'verbose_name_plural': 'atendimentos do site',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='brevo_marketing_list_id',
            field=models.PositiveIntegerField(blank=True, help_text='Lista de contatos que recebera as inscricoes realizadas pela landing page.', null=True, verbose_name='ID da lista Brevo'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='contact_text',
            field=models.TextField(default='Diga o que voce sente, o que procura ou qual rotina deseja construir. A equipe responde pelo WhatsApp e indica o caminho mais adequado.', verbose_name='texto do contato'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='contact_title',
            field=models.CharField(default='Conte seu caso. A Lume orienta o primeiro passo.', max_length=180, verbose_name='titulo do contato'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='faq_title',
            field=models.CharField(default='Informacoes essenciais.', max_length=160, verbose_name='titulo das duvidas'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='footer_text',
            field=models.TextField(default='Cuidado presencial e continuidade para uma rotina com mais movimento e seguranca.', verbose_name='texto do rodape'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='gallery_text',
            field=models.TextField(default='Registros do estudio ajudam voce a sentir o ambiente antes de marcar a primeira visita.', verbose_name='texto da galeria'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='gallery_title',
            field=models.CharField(default='Um pouco do cuidado que acontece na Lume.', max_length=180, verbose_name='titulo da galeria'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='hero_eyebrow',
            field=models.CharField(default='Pilates e fisioterapia em Penedo, AL', max_length=120, verbose_name='chamada acima do titulo'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='homecare_text',
            field=models.TextField(default='A biblioteca de aulas gravadas apoia a rotina do paciente entre os atendimentos, com conteudos organizados por foco, nivel e duracao.', verbose_name='texto do Lume em casa'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='homecare_title',
            field=models.CharField(default='Lume em casa entra depois da orientacao presencial.', max_length=180, verbose_name='titulo do Lume em casa'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='homecare_video_url',
            field=models.URLField(blank=True, verbose_name='video do Lume em casa'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='newsletter_text',
            field=models.CharField(default='Conteudos de cuidado, agenda e novidades do studio.', max_length=255, verbose_name='texto da lista de e-mail'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='newsletter_title',
            field=models.CharField(default='Receba novidades da Lume', max_length=140, verbose_name='titulo da lista de e-mail'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='plans_text',
            field=models.TextField(default='Os planos ajudam a manter frequencia. Se voce ainda nao sabe qual escolher, fale com a equipe antes de decidir.', verbose_name='texto dos planos'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='plans_title',
            field=models.CharField(default='Planos para manter sua rotina de cuidado.', max_length=180, verbose_name='titulo dos planos'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='services_text',
            field=models.TextField(default='Voce pode chegar com dor, busca por movimento, tensao acumulada ou vontade de manter uma rotina mais saudavel. A equipe ajuda a traduzir isso em um caminho de cuidado.', verbose_name='texto dos atendimentos'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='services_title',
            field=models.CharField(default='Atendimentos para cuidar do corpo com clareza e acolhimento.', max_length=180, verbose_name='titulo dos atendimentos'),
        ),
        migrations.AddField(
            model_name='websitesettings',
            name='testimonials_title',
            field=models.CharField(default='O que nossos pacientes sentem.', max_length=180, verbose_name='titulo dos depoimentos'),
        ),
    ]
