# Generated by Django 5.2.15 on 2026-07-14 21:11

from django.db import migrations, models


def preserve_current_public_copy(apps, schema_editor):
    WebsiteSettings = apps.get_model("website", "WebsiteSettings")
    WebsiteSettings.objects.filter(
        hero_title="Movimento consciente para reabilitar, prevenir e viver melhor."
    ).update(hero_title="Cuidado presencial para voltar a se mover com seguranca.")
    WebsiteSettings.objects.filter(
        hero_subtitle=(
            "Pilates, fisioterapia, massagem e Reiki em um atendimento acolhedor, "
            "humano e pensado para a sua rotina."
        )
    ).update(
        hero_subtitle=(
            "A Lume combina fisioterapia, Pilates e terapias corporais em uma rotina orientada, "
            "com escuta proxima desde o primeiro contato."
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_websitegalleryitem_websitenewslettersubscriber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesettings',
            name='hero_subtitle',
            field=models.TextField(default='A Lume combina fisioterapia, Pilates e terapias corporais em uma rotina orientada, com escuta proxima desde o primeiro contato.', verbose_name='subtitulo principal'),
        ),
        migrations.AlterField(
            model_name='websitesettings',
            name='hero_title',
            field=models.CharField(default='Cuidado presencial para voltar a se mover com seguranca.', max_length=180, verbose_name='titulo principal'),
        ),
        migrations.RunPython(preserve_current_public_copy, migrations.RunPython.noop),
    ]
