# Generated by Django 5.2.15 on 2026-06-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('full_name', models.CharField(max_length=180, verbose_name='nome completo')),
                ('role', models.CharField(choices=[('admin', 'Administracao'), ('reception', 'Recepcao'), ('finance', 'Financeiro')], max_length=30, verbose_name='funcao')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='data de admissao')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'funcionario',
                'verbose_name_plural': 'funcionarios',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('full_name', models.CharField(max_length=180, verbose_name='nome completo')),
                ('specialty', models.CharField(choices=[('physiotherapy', 'Fisioterapia'), ('pilates', 'Pilates'), ('massage', 'Massagem'), ('reiki', 'Reiki'), ('other', 'Outro')], max_length=30, verbose_name='especialidade')),
                ('registration_number', models.CharField(blank=True, max_length=80, verbose_name='registro profissional')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('bio', models.TextField(blank=True, verbose_name='observacoes')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'profissional',
                'verbose_name_plural': 'profissionais',
                'ordering': ['full_name'],
            },
        ),
    ]
