# Generated by Django 5.2.15 on 2026-06-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, upload_to='employees/photos/', verbose_name='foto'),
        ),
        migrations.AddField(
            model_name='professional',
            name='photo',
            field=models.ImageField(blank=True, upload_to='professionals/photos/', verbose_name='foto'),
        ),
    ]
