# Generated by Django 5.2.15 on 2026-06-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_employee_photo_professional_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='exclusao solicitada em'),
        ),
        migrations.AddField(
            model_name='professional',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='exclusao solicitada em'),
        ),
    ]
