# Generated by Django 5.2.15 on 2026-06-29 04:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0005_serviceplan_deletion_requested_at'),
        ('patients', '0006_patient_deletion_requested_at'),
        ('scheduling', '0004_professionalavailability_deletion_requested_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('kind', models.CharField(choices=[('service_plan', 'Compra de plano'), ('payment', 'Pagamento de mensalidade')], max_length=30, verbose_name='tipo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Aguardando pagamento'), ('paid', 'Pago'), ('failed', 'Falhou'), ('canceled', 'Cancelado'), ('expired', 'Expirado')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('provider', models.CharField(choices=[('asaas', 'Asaas'), ('manual', 'Manual')], default='asaas', max_length=20, verbose_name='provedor')),
                ('customer_name', models.CharField(max_length=180, verbose_name='nome')),
                ('customer_document', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('customer_birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('customer_phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='valor')),
                ('external_reference', models.CharField(blank=True, max_length=80, unique=True, verbose_name='referencia externa')),
                ('provider_customer_id', models.CharField(blank=True, max_length=120, verbose_name='cliente no provedor')),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='pagamento no provedor')),
                ('checkout_url', models.URLField(blank=True, max_length=500, verbose_name='URL de pagamento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processado em')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='payload do provedor')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('created_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_orders', to='billing.membership')),
                ('created_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_orders', to='scheduling.servicepackage')),
                ('created_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checkout_orders', to='patients.patient')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_orders', to='patients.patient')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_orders', to='billing.payment')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkout_orders', to='billing.serviceplan')),
            ],
            options={
                'verbose_name': 'pedido de checkout',
                'verbose_name_plural': 'pedidos de checkout',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckoutPaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('provider', models.CharField(default='asaas', max_length=20, verbose_name='provedor')),
                ('event_id', models.CharField(max_length=160, unique=True, verbose_name='ID do evento')),
                ('event_type', models.CharField(max_length=80, verbose_name='tipo')),
                ('provider_payment_id', models.CharField(blank=True, max_length=120, verbose_name='pagamento no provedor')),
                ('external_reference', models.CharField(blank=True, max_length=80, verbose_name='referencia externa')),
                ('access_token_valid', models.BooleanField(default=False, verbose_name='token valido')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processado em')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='checkout.checkoutorder')),
            ],
            options={
                'verbose_name': 'evento de pagamento do checkout',
                'verbose_name_plural': 'eventos de pagamento do checkout',
                'ordering': ['-created_at'],
            },
        ),
    ]
