# Generated by Django 5.2.15 on 2026-06-30 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutMerchantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('provider', models.CharField(choices=[('asaas', 'Asaas')], default='asaas', max_length=20, verbose_name='provedor')),
                ('account_type', models.CharField(choices=[('own_account', 'Conta propria'), ('subaccount', 'Subconta comercial')], default='subaccount', max_length=30, verbose_name='modelo de recebimento')),
                ('status', models.CharField(choices=[('not_started', 'Nao iniciado'), ('draft', 'Rascunho'), ('pending_provider', 'Em analise'), ('active', 'Ativa'), ('action_required', 'Acao necessaria'), ('rejected', 'Rejeitada'), ('disabled', 'Desativada')], db_index=True, default='not_started', max_length=30, verbose_name='status')),
                ('legal_name', models.CharField(blank=True, max_length=180, verbose_name='razao social/nome')),
                ('trade_name', models.CharField(blank=True, max_length=180, verbose_name='nome fantasia')),
                ('document', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail financeiro')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone financeiro')),
                ('provider_account_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='conta no provedor')),
                ('provider_wallet_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='wallet/subconta no provedor')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='metadados do provedor')),
                ('onboarding_started_at', models.DateTimeField(blank=True, null=True, verbose_name='cadastro iniciado em')),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='cadastro concluido em')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='ultima sincronizacao')),
                ('last_error', models.TextField(blank=True, verbose_name='ultimo erro')),
                ('active', models.BooleanField(default=True, verbose_name='ativa para novos pedidos')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
            ],
            options={
                'verbose_name': 'conta recebedora do checkout',
                'verbose_name_plural': 'contas recebedoras do checkout',
                'ordering': ['provider', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('provider',), name='unique_active_checkout_merchant_provider')],
            },
        ),
        migrations.AddField(
            model_name='checkoutorder',
            name='merchant_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='checkout.checkoutmerchantaccount', verbose_name='conta recebedora'),
        ),
    ]
