# Generated by Django 5.2.15 on 2026-06-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_checkoutmerchantaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutmerchantaccount',
            name='address',
            field=models.CharField(blank=True, max_length=180, verbose_name='endereco'),
        ),
        migrations.AddField(
            model_name='checkoutmerchantaccount',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='numero'),
        ),
        migrations.AddField(
            model_name='checkoutmerchantaccount',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='checkoutmerchantaccount',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='checkoutmerchantaccount',
            name='company_type',
            field=models.CharField(blank=True, choices=[('individual', 'Pessoa fisica'), ('mei', 'MEI'), ('limited', 'LTDA'), ('association', 'Associacao'), ('other', 'Outro')], max_length=20, verbose_name='tipo de pessoa/empresa'),
        ),
        migrations.AddField(
            model_name='checkoutmerchantaccount',
            name='complement',
            field=models.CharField(blank=True, max_length=80, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='checkoutmerchantaccount',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='renda/faturamento mensal'),
        ),
        migrations.AddField(
            model_name='checkoutmerchantaccount',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='checkoutmerchantaccount',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='checkoutmerchantaccount',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='responsavel financeiro'),
        ),
        migrations.AddField(
            model_name='checkoutmerchantaccount',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
    ]
