# Generated by Django 5.2.15 on 2026-06-29 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_professionalnote_structured_data_and_more'),
        ('team', '0002_employee_photo_professional_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomecareCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('display_order', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='ordem')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'categoria de conteudo',
                'verbose_name_plural': 'categorias de conteudo',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HomecarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], default='monthly', max_length=20, verbose_name='ciclo')),
                ('display_order', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='ordem')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('public_checkout_enabled', models.BooleanField(default=True, verbose_name='checkout publico ativo')),
                ('provider_plan_reference', models.CharField(blank=True, max_length=120, verbose_name='referencia no provedor')),
            ],
            options={
                'verbose_name': 'plano do canal',
                'verbose_name_plural': 'planos do canal',
                'ordering': ['display_order', 'monthly_price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HomecareSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('trialing', 'Teste'), ('active', 'Ativa'), ('past_due', 'Em atraso'), ('canceled', 'Cancelada'), ('expired', 'Expirada')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('source', models.CharField(choices=[('manual', 'Liberacao manual'), ('checkout', 'Checkout'), ('imported', 'Importada')], default='manual', max_length=20, verbose_name='origem')),
                ('provider', models.CharField(choices=[('asaas', 'Asaas'), ('manual', 'Manual')], default='manual', max_length=20, verbose_name='provedor')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='inicio')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='inicio do periodo')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='fim do periodo')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelado em')),
                ('provider_customer_id', models.CharField(blank=True, max_length=120, verbose_name='cliente no provedor')),
                ('provider_subscription_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='assinatura no provedor')),
                ('provider_payment_id', models.CharField(blank=True, max_length=120, verbose_name='pagamento no provedor')),
                ('external_reference', models.CharField(blank=True, max_length=80, unique=True, verbose_name='referencia externa')),
                ('checkout_url', models.URLField(blank=True, max_length=500, verbose_name='URL de checkout')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homecare_subscriptions', to='patients.patient')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='homecare.homecareplan')),
            ],
            options={
                'verbose_name': 'assinatura do canal',
                'verbose_name_plural': 'assinaturas do canal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomecarePaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('provider', models.CharField(default='asaas', max_length=20, verbose_name='provedor')),
                ('event_id', models.CharField(max_length=160, unique=True, verbose_name='ID do evento')),
                ('event_type', models.CharField(max_length=80, verbose_name='tipo')),
                ('provider_subscription_id', models.CharField(blank=True, max_length=120, verbose_name='assinatura no provedor')),
                ('provider_payment_id', models.CharField(blank=True, max_length=120, verbose_name='pagamento no provedor')),
                ('external_reference', models.CharField(blank=True, max_length=80, verbose_name='referencia externa')),
                ('access_token_valid', models.BooleanField(default=False, verbose_name='token valido')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processado em')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homecare_payment_events', to='patients.patient')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='homecare.homecaresubscription')),
            ],
            options={
                'verbose_name': 'evento de pagamento do canal',
                'verbose_name_plural': 'eventos de pagamento do canal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomecareVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=160, verbose_name='titulo')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('specialty', models.CharField(blank=True, max_length=30, verbose_name='area')),
                ('difficulty', models.CharField(choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediario'), ('advanced', 'Avancado')], default='beginner', max_length=20, verbose_name='nivel')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, default=0, verbose_name='duracao em segundos')),
                ('temporary_file', models.FileField(blank=True, upload_to='homecare/uploads/', verbose_name='arquivo temporario')),
                ('thumbnail', models.ImageField(blank=True, upload_to='homecare/thumbnails/', verbose_name='capa')),
                ('provider', models.CharField(choices=[('bunny', 'Bunny Stream'), ('manual', 'Manual')], default='bunny', max_length=20, verbose_name='provedor')),
                ('provider_video_id', models.CharField(blank=True, db_index=True, max_length=160, verbose_name='ID do video no provedor')),
                ('provider_library_id', models.CharField(blank=True, max_length=160, verbose_name='ID da biblioteca')),
                ('provider_embed_url', models.URLField(blank=True, max_length=500, verbose_name='URL de embed')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='payload do provedor')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('queued', 'Na fila'), ('uploading', 'Enviando'), ('processing', 'Processando'), ('ready', 'Pronto'), ('failed', 'Falhou'), ('archived', 'Arquivado')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('upload_error', models.TextField(blank=True, verbose_name='erro de upload')),
                ('is_published', models.BooleanField(default=False, verbose_name='publicado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homecare_videos', to='team.professional')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='homecare.homecarecategory')),
            ],
            options={
                'verbose_name': 'video do canal',
                'verbose_name_plural': 'videos do canal',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomecareUploadJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('running', 'Processando'), ('done', 'Concluido'), ('failed', 'Falhou')], db_index=True, default='queued', max_length=20, verbose_name='status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('error_message', models.TextField(blank=True, verbose_name='erro')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_jobs', to='homecare.homecarevideo')),
            ],
            options={
                'verbose_name': 'fila de upload do canal',
                'verbose_name_plural': 'fila de uploads do canal',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomecareVideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('watched_seconds', models.PositiveIntegerField(default=0, verbose_name='segundos assistidos')),
                ('completed', models.BooleanField(default=False, verbose_name='concluido')),
                ('last_watched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='assistido em')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homecare_video_progress', to='patients.patient')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='homecare.homecarevideo')),
            ],
            options={
                'verbose_name': 'progresso de video',
                'verbose_name_plural': 'progressos de video',
                'ordering': ['-last_watched_at'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'video'), name='unique_homecare_progress')],
            },
        ),
    ]
