# Generated by Django 5.2.15 on 2026-06-29 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_serviceplan_deletion_requested_at'),
        ('homecare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarepaymentevent',
            name='finance_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homecare_payment_events', to='billing.charge', verbose_name='receita no financeiro'),
        ),
    ]
