# Generated by Django 5.2.15 on 2026-06-29 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0002_homecarepaymentevent_finance_charge'),
        ('team', '0003_employee_deletion_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarevideo',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homecare_videos', to='team.professional', verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='homecarevideo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='homecare.homecarecategory', verbose_name='categoria'),
        ),
    ]
