# Generated by Django 5.2.15 on 2026-06-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0003_alter_homecarevideo_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarevideo',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Data e horario em que o video passa a aparecer para assinantes.', null=True, verbose_name='lancamento programado'),
        ),
    ]
