# Generated by Django 5.2.15 on 2026-06-29 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0004_homecarevideo_scheduled_publish_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomecareVideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('content', models.TextField(verbose_name='comentario')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homecare_video_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='homecare.homecarevideocomment', verbose_name='comentario respondido')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='homecare.homecarevideo')),
            ],
            options={
                'verbose_name': 'comentario de video do Lume em casa',
                'verbose_name_plural': 'comentarios de videos do Lume em casa',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['video', 'is_active', 'created_at'], name='homecare_ho_video_i_a393e2_idx'), models.Index(fields=['parent', 'is_active', 'created_at'], name='homecare_ho_parent__5d00b6_idx'), models.Index(fields=['author', '-created_at'], name='homecare_ho_author__ba89ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomecareVideoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homecare_video_likes', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='homecare.homecarevideo')),
            ],
            options={
                'verbose_name': 'curtida de video do Lume em casa',
                'verbose_name_plural': 'curtidas de videos do Lume em casa',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('video', 'user'), name='unique_homecare_video_like_per_user')],
            },
        ),
    ]
