# Generated by Django 5.2.15 on 2026-06-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0005_homecarevideocomment_homecarevideolike'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarevideo',
            name='local_video_file',
            field=models.FileField(blank=True, upload_to='homecare/private/videos/', verbose_name='arquivo local protegido'),
        ),
        migrations.AlterField(
            model_name='homecarevideo',
            name='provider',
            field=models.CharField(choices=[('local', 'VPS protegida'), ('bunny', 'Bunny Stream'), ('manual', 'Manual')], default='local', max_length=20, verbose_name='provedor'),
        ),
    ]
