"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LUME_DESKTOP = config("LUME_DESKTOP", default=False, cast=bool)
LUME_DATA_DIR = Path(config("LUME_DATA_DIR", default=str(BASE_DIR))).resolve()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="lume-local-dev-secret-key-2026-7f4b2c91a8d5e3f0-change-before-production",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)
ENVIRONMENT = config("ENVIRONMENT", default="development")
IS_PRODUCTION = ENVIRONMENT.lower() == "production" or not DEBUG
LUME_STRICT_PRODUCTION = config("LUME_STRICT_PRODUCTION", default=IS_PRODUCTION, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="127.0.0.1,localhost,testserver",
    cast=lambda value: [host.strip() for host in value.split(",") if host.strip()],
)

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="",
    cast=lambda value: [origin.strip() for origin in value.split(",") if origin.strip()],
)
PUBLIC_BASE_URL = config("PUBLIC_BASE_URL", default="")


def _looks_like_placeholder(value):
    lowered = (value or "").lower()
    markers = (
        "troque",
        "change-before-production",
        "lume_dev_password",
        "dev-local",
        "ip_da",
        "seudominio",
        "example",
    )
    return not lowered or any(marker in lowered for marker in markers)


def _has_public_host(hosts):
    local_hosts = {"127.0.0.1", "localhost", "testserver", "0.0.0.0"}
    return any(host not in local_hosts and not host.startswith("127.") for host in hosts)


def _has_public_https_origin(origins):
    return any(origin.startswith("https://") and "localhost" not in origin and "127.0.0.1" not in origin for origin in origins)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'accounts',
    'core',
    'patients',
    'team',
    'billing',
    'scheduling',
    'reports',
    'fiscal',
    'mobile',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.CurrentUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = config("DB_ENGINE", default="sqlite").lower()
POSTGRES_PASSWORD = config("POSTGRES_PASSWORD", default="lume_dev_password")

if LUME_STRICT_PRODUCTION and IS_PRODUCTION:
    production_errors = []
    if DEBUG:
        production_errors.append("DEBUG precisa ser False em producao.")
    if _looks_like_placeholder(SECRET_KEY) or len(SECRET_KEY) < 50:
        production_errors.append("SECRET_KEY precisa ser unica, forte e ter pelo menos 50 caracteres.")
    if not _has_public_host(ALLOWED_HOSTS):
        production_errors.append("ALLOWED_HOSTS precisa incluir o dominio publico da aplicacao.")
    if not _has_public_https_origin(CSRF_TRUSTED_ORIGINS):
        production_errors.append("CSRF_TRUSTED_ORIGINS precisa incluir a origem HTTPS publica.")
    if DB_ENGINE != "postgres":
        production_errors.append("DB_ENGINE precisa ser postgres em producao VPS.")
    if _looks_like_placeholder(POSTGRES_PASSWORD):
        production_errors.append("POSTGRES_PASSWORD precisa ser forte e nao pode usar valor de exemplo.")
    if production_errors:
        raise ImproperlyConfigured("Configuracao de producao invalida: " + " ".join(production_errors))

if DB_ENGINE == "postgres":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("POSTGRES_DB", default="lume"),
            "USER": config("POSTGRES_USER", default="lume"),
            "PASSWORD": POSTGRES_PASSWORD,
            "HOST": config("POSTGRES_HOST", default="db"),
            "PORT": config("POSTGRES_PORT", default="5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": LUME_DATA_DIR / "db.sqlite3" if LUME_DESKTOP else BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = Path(config("STATIC_ROOT", default=str(BASE_DIR / 'staticfiles'))).resolve()
STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedManifestStaticFilesStorage"
    if IS_PRODUCTION
    else "django.contrib.staticfiles.storage.StaticFilesStorage"
)
MEDIA_URL = 'media/'
DEFAULT_MEDIA_ROOT = LUME_DATA_DIR / 'media' if LUME_DESKTOP else BASE_DIR / 'media'
MEDIA_ROOT = Path(config("MEDIA_ROOT", default=str(DEFAULT_MEDIA_ROOT))).resolve()

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="Lume Gestao <nao-responda@lume.local>")
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=15, cast=int)

GOOGLE_CALENDAR_CLIENT_ID = config("GOOGLE_CALENDAR_CLIENT_ID", default="")
GOOGLE_CALENDAR_CLIENT_SECRET = config("GOOGLE_CALENDAR_CLIENT_SECRET", default="")
GOOGLE_CALENDAR_TIMEOUT = config("GOOGLE_CALENDAR_TIMEOUT", default=15, cast=int)
GOOGLE_CALENDAR_SYNC_ENABLED = config("GOOGLE_CALENDAR_SYNC_ENABLED", default=True, cast=bool)

WHATSAPP_PROVIDER = config("WHATSAPP_PROVIDER", default="meta")
WHATSAPP_DRY_RUN = config("WHATSAPP_DRY_RUN", default=True, cast=bool)
WHATSAPP_META_API_VERSION = config("WHATSAPP_META_API_VERSION", default="v23.0")
WHATSAPP_META_ACCESS_TOKEN = config("WHATSAPP_META_ACCESS_TOKEN", default="")
WHATSAPP_META_PHONE_NUMBER_ID = config("WHATSAPP_META_PHONE_NUMBER_ID", default="")
WHATSAPP_EMBEDDED_APP_ID = config("WHATSAPP_EMBEDDED_APP_ID", default="")
WHATSAPP_EMBEDDED_CONFIG_ID = config("WHATSAPP_EMBEDDED_CONFIG_ID", default="")
WHATSAPP_EMBEDDED_APP_SECRET = config("WHATSAPP_EMBEDDED_APP_SECRET", default="")
WHATSAPP_TIMEOUT = config("WHATSAPP_TIMEOUT", default=15, cast=int)
REST_ENABLE_BASIC_AUTH = config("REST_ENABLE_BASIC_AUTH", default=False, cast=bool)
REST_ENABLE_TOKEN_AUTH = config("REST_ENABLE_TOKEN_AUTH", default=True, cast=bool)
REST_ENABLE_THROTTLING = config("REST_ENABLE_THROTTLING", default=False, cast=bool)
REST_ANON_THROTTLE_RATE = config("REST_ANON_THROTTLE_RATE", default="30/min")
REST_USER_THROTTLE_RATE = config("REST_USER_THROTTLE_RATE", default="1000/hour")
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=IS_PRODUCTION, cast=bool)
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=IS_PRODUCTION, cast=bool)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=IS_PRODUCTION, cast=bool)
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=31536000 if IS_PRODUCTION else 0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=IS_PRODUCTION,
    cast=bool,
)
SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=IS_PRODUCTION, cast=bool)
SECURE_CONTENT_TYPE_NOSNIFF = config("SECURE_CONTENT_TYPE_NOSNIFF", default=True, cast=bool)
SECURE_REFERRER_POLICY = config("SECURE_REFERRER_POLICY", default="same-origin")
X_FRAME_OPTIONS = config("X_FRAME_OPTIONS", default="DENY")
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = config("USE_X_FORWARDED_HOST", default=IS_PRODUCTION, cast=bool)

if LUME_STRICT_PRODUCTION and IS_PRODUCTION:
    security_errors = []
    if not SECURE_SSL_REDIRECT:
        security_errors.append("SECURE_SSL_REDIRECT precisa ser True.")
    if not SESSION_COOKIE_SECURE:
        security_errors.append("SESSION_COOKIE_SECURE precisa ser True.")
    if not CSRF_COOKIE_SECURE:
        security_errors.append("CSRF_COOKIE_SECURE precisa ser True.")
    if SECURE_HSTS_SECONDS < 31536000:
        security_errors.append("SECURE_HSTS_SECONDS precisa ser pelo menos 31536000.")
    if security_errors:
        raise ImproperlyConfigured("Configuracao HTTPS de producao invalida: " + " ".join(security_errors))

_REST_AUTHENTICATION_CLASSES = ['rest_framework.authentication.SessionAuthentication']
if REST_ENABLE_TOKEN_AUTH:
    _REST_AUTHENTICATION_CLASSES.append('rest_framework.authentication.TokenAuthentication')
if REST_ENABLE_BASIC_AUTH:
    _REST_AUTHENTICATION_CLASSES.append('rest_framework.authentication.BasicAuthentication')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': _REST_AUTHENTICATION_CLASSES,
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

if REST_ENABLE_THROTTLING:
    REST_FRAMEWORK.update(
        {
            'DEFAULT_THROTTLE_CLASSES': [
                'rest_framework.throttling.AnonRateThrottle',
                'rest_framework.throttling.UserRateThrottle',
            ],
            'DEFAULT_THROTTLE_RATES': {
                'anon': REST_ANON_THROTTLE_RATE,
                'user': REST_USER_THROTTLE_RATE,
            },
        }
    )

LOG_LEVEL = config("LOG_LEVEL", default="INFO")
DJANGO_LOG_LEVEL = config("DJANGO_LOG_LEVEL", default=LOG_LEVEL)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console": {
            "format": "%(levelname)s %(asctime)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
