# Generated by Django 5.2.15 on 2026-06-29 05:15

import django.core.validators
import django.db.models.deletion
import lume_connect.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('content', models.TextField(verbose_name='comentario')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'comentario do Lume Connect',
                'verbose_name_plural': 'comentarios do Lume Connect',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('content', models.TextField(blank=True, verbose_name='conteudo')),
                ('image', models.ImageField(blank=True, upload_to='lume_connect/posts/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), lume_connect.models.validate_connect_image_size], verbose_name='imagem')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='fixado')),
                ('is_announcement', models.BooleanField(default=False, verbose_name='comunicado')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post do Lume Connect',
                'verbose_name_plural': 'posts do Lume Connect',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('like', 'Curtida'), ('comment', 'Comentario')], max_length=20, verbose_name='tipo')),
                ('is_read', models.BooleanField(default=False, verbose_name='lida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='lume_connect.connectcomment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_notifications', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='lume_connect.connectpost')),
            ],
            options={
                'verbose_name': 'notificacao do Lume Connect',
                'verbose_name_plural': 'notificacoes do Lume Connect',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='lume_connect.connectpost')),
            ],
            options={
                'verbose_name': 'curtida do Lume Connect',
                'verbose_name_plural': 'curtidas do Lume Connect',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='connectcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lume_connect.connectpost'),
        ),
        migrations.AddIndex(
            model_name='connectpost',
            index=models.Index(fields=['is_active', '-is_pinned', '-created_at'], name='lume_connec_is_acti_977b43_idx'),
        ),
        migrations.AddIndex(
            model_name='connectpost',
            index=models.Index(fields=['author', '-created_at'], name='lume_connec_author__4968d1_idx'),
        ),
        migrations.AddIndex(
            model_name='connectnotification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='lume_connec_recipie_6ea4ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='connectlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_lume_connect_like_per_user'),
        ),
        migrations.AddIndex(
            model_name='connectcomment',
            index=models.Index(fields=['post', 'is_active', 'created_at'], name='lume_connec_post_id_3d5614_idx'),
        ),
        migrations.AddIndex(
            model_name='connectcomment',
            index=models.Index(fields=['author', '-created_at'], name='lume_connec_author__feaa1b_idx'),
        ),
    ]
