# Generated by Django 5.2.15 on 2026-06-29 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lume_connect', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectShareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_platform', models.CharField(choices=[('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('native', 'Compartilhamento nativo'), ('download', 'Download da imagem'), ('copy_caption', 'Copia de legenda'), ('other', 'Outra rede')], max_length=30, verbose_name='destino')),
                ('generated_caption', models.TextField(blank=True, verbose_name='legenda gerada')),
                ('final_caption', models.TextField(blank=True, verbose_name='legenda final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_logs', to='lume_connect.connectpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connect_share_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de compartilhamento do Lume Connect',
                'verbose_name_plural': 'registros de compartilhamento do Lume Connect',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', '-created_at'], name='lume_connec_post_id_a88e7f_idx'), models.Index(fields=['user', '-created_at'], name='lume_connec_user_id_8abcfa_idx'), models.Index(fields=['target_platform', '-created_at'], name='lume_connec_target__9808de_idx')],
            },
        ),
    ]
