# Generated by Django 5.2.15 on 2026-06-29 16:34

import django.core.validators
import lume_connect.models
from django.db import migrations, models


def backfill_media_type(apps, schema_editor):
    ConnectPost = apps.get_model("lume_connect", "ConnectPost")
    ConnectPost.objects.exclude(image="").update(media_type="image")


class Migration(migrations.Migration):

    dependencies = [
        ('lume_connect', '0002_connectsharelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectpost',
            name='is_short_video',
            field=models.BooleanField(default=False, verbose_name='video curto'),
        ),
        migrations.AddField(
            model_name='connectpost',
            name='media_type',
            field=models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('video', 'Video'), ('short_video', 'Video curto')], default='text', max_length=20, verbose_name='tipo de midia'),
        ),
        migrations.AddField(
            model_name='connectpost',
            name='video',
            field=models.FileField(blank=True, upload_to='lume_connect/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov']), lume_connect.models.validate_connect_video_size], verbose_name='video'),
        ),
        migrations.AddField(
            model_name='connectpost',
            name='video_duration_seconds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='duracao do video em segundos'),
        ),
        migrations.AddField(
            model_name='connectpost',
            name='video_size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='tamanho do video em bytes'),
        ),
        migrations.AddField(
            model_name='connectpost',
            name='video_thumbnail',
            field=models.ImageField(blank=True, upload_to='lume_connect/video_thumbnails/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), lume_connect.models.validate_connect_image_size], verbose_name='capa do video'),
        ),
        migrations.RunPython(backfill_media_type, migrations.RunPython.noop),
    ]
