# Generated by Django 5.2.15 on 2026-06-29 18:10

import django.core.validators
import lume_connect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lume_connect', '0003_connectpost_is_short_video_connectpost_media_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectpost',
            name='video',
            field=models.FileField(blank=True, upload_to='lume_connect/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'webm']), lume_connect.models.validate_connect_video_size], verbose_name='video'),
        ),
    ]
