# Generated by Django 5.2.15 on 2026-06-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('full_name', models.CharField(max_length=180, verbose_name='nome completo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('emergency_contact', models.CharField(blank=True, max_length=180, verbose_name='contato de emergencia')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='endereco')),
                ('clinical_notes', models.TextField(blank=True, verbose_name='observacoes clinicas')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['full_name'],
            },
        ),
    ]
