# Generated by Django 5.2.15 on 2026-06-24 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=140, verbose_name='titulo')),
                ('body', models.TextField(verbose_name='anotacao')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_notes', to='patients.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_notes', to='team.professional')),
            ],
            options={
                'verbose_name': 'anotacao profissional',
                'verbose_name_plural': 'anotacoes profissionais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalPatientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='observacoes')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_assignments', to='patients.patient')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_assignments', to='team.professional')),
            ],
            options={
                'verbose_name': 'vinculo paciente-profissional',
                'verbose_name_plural': 'vinculos paciente-profissional',
                'ordering': ['patient__full_name', 'professional__full_name'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'professional'), name='unique_patient_professional_assignment')],
            },
        ),
    ]
