# Generated by Django 5.2.15 on 2026-06-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_professionalnote_professionalpatientassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(blank=True, upload_to='patients/photos/', verbose_name='foto'),
        ),
    ]
