# Generated by Django 5.2.15 on 2026-06-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalnote',
            name='clinical_status',
            field=models.CharField(blank=True, choices=[('improved', 'Melhorou'), ('stable', 'Estavel'), ('worsened', 'Piorou'), ('reassess', 'Reavaliar')], max_length=20, verbose_name='evolucao clinica'),
        ),
        migrations.AddField(
            model_name='professionalnote',
            name='conduct',
            field=models.CharField(blank=True, choices=[('keep', 'Manter plano'), ('progress', 'Progredir exercicios'), ('reduce', 'Reduzir carga'), ('reassess', 'Reavaliar conduta')], max_length=20, verbose_name='conduta'),
        ),
        migrations.AddField(
            model_name='professionalnote',
            name='exercise_groups',
            field=models.JSONField(blank=True, default=list, verbose_name='selecoes de exercicios'),
        ),
        migrations.AddField(
            model_name='professionalnote',
            name='objective',
            field=models.CharField(blank=True, max_length=220, verbose_name='objetivo'),
        ),
        migrations.AddField(
            model_name='professionalnote',
            name='pain_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nivel de dor'),
        ),
        migrations.AddField(
            model_name='professionalnote',
            name='record_type',
            field=models.CharField(choices=[('initial', 'Avaliacao inicial'), ('evolution', 'Evolucao'), ('reassessment', 'Reavaliacao'), ('discharge', 'Alta')], default='evolution', max_length=20, verbose_name='tipo de registro'),
        ),
        migrations.AddField(
            model_name='professionalnote',
            name='session_focus',
            field=models.CharField(blank=True, choices=[('pilates', 'Pilates'), ('physiotherapy', 'Fisioterapia'), ('strength', 'Fortalecimento'), ('mobility', 'Mobilidade'), ('pain', 'Controle de dor'), ('posture', 'Postura')], max_length=30, verbose_name='foco do atendimento'),
        ),
        migrations.AlterField(
            model_name='professionalnote',
            name='body',
            field=models.TextField(blank=True, verbose_name='observacoes'),
        ),
    ]
