# Generated by Django 5.2.15 on 2026-06-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_professionalnote_clinical_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalnote',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='dados estruturados'),
        ),
        migrations.AlterField(
            model_name='professionalnote',
            name='record_type',
            field=models.CharField(choices=[('clinical_evaluation', 'Avaliacao clinica'), ('diagnosis', 'Diagnostico'), ('physical_exam', 'Exame fisico clinico'), ('daily_evolution', 'Evolucao diaria'), ('initial', 'Avaliacao inicial'), ('evolution', 'Evolucao'), ('reassessment', 'Reavaliacao'), ('discharge', 'Alta')], default='daily_evolution', max_length=30, verbose_name='tipo de registro'),
        ),
    ]
