# Generated by Django 5.2.15 on 2026-07-13 05:38

import django.db.models.deletion
from django.db import migrations, models


def populate_referral_codes(apps, schema_editor):
    Patient = apps.get_model("patients", "Patient")
    for patient in Patient.objects.filter(active=True, referral_code__isnull=True).iterator():
        patient.referral_code = f"LUME-{patient.pk:08X}"
        patient.save(update_fields=["referral_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_deletion_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='referral_code',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True, verbose_name='codigo de indicacao'),
        ),
        migrations.CreateModel(
            name='PatientReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('prospect_name', models.CharField(max_length=180, verbose_name='nome da pessoa indicada')),
                ('prospect_phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('prospect_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('status', models.CharField(choices=[('new', 'Novo contato'), ('contacted', 'Contatado'), ('evaluation_scheduled', 'Avaliacao agendada'), ('converted', 'Convertido'), ('lost', 'Perdido')], default='new', max_length=30, verbose_name='status')),
                ('contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='contatado em')),
                ('converted_at', models.DateTimeField(blank=True, null=True, verbose_name='convertido em')),
                ('benefit_note', models.CharField(blank=True, max_length=220, verbose_name='beneficio concedido')),
                ('benefit_granted_at', models.DateTimeField(blank=True, null=True, verbose_name='beneficio concedido em')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes internas')),
                ('converted_patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_origin', to='patients.patient')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='patients.patient')),
            ],
            options={
                'verbose_name': 'indicacao',
                'verbose_name_plural': 'indicacoes',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.RunPython(populate_referral_codes, migrations.RunPython.noop),
    ]
